### ISSUE TITLE
HD address 0x into "41..." or "T" one?

### ISSUE THREAD

**Issue by ally9335** [DoctorLai/Tron-FAQ#2]
If I generate a HD address this way:

```
const node = ethers.utils.HDNode.fromMnemonic(process.env.MNEMONIC)
const dp = `m/44'/195'/0'/0'`;
const i = 1;
const wallet = node.derivePath(`${dp}/${i}`)
console.log(wallet.address)
```

it'll start with `0x` --> `"0xfdsfds.........43`

How to convert it into a valid Tron address now? The one that starts with "41" or "T".

**Comment by DoctorLai** [comment]
https://developers.tron.network/reference/frommnemonic
